### ISSUE TITLE
Changing the number of MIG divisions confuses Slurm

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/puppet-magic_castle#361] opened 2024-05-23 13:05 UTC
I went from a config that had 4 MIG divisions to a node that had 3, and this showed up in the Slurm logs and the nodes became in an "invalid" state
```
May 23 12:49:52 mgmt1.int.p2-ecole.calculquebec.cloud slurmctld[80708]: slurmctld: _node_config_validate: gres/gpu: Count changed on node nodegpu1 (4 != 3)
May 23 12:49:52 mgmt1.int.p2-ecole.calculquebec.cloud slurmctld[80708]: slurmctld: error: Setting node nodegpu1 state to INVAL with reason:gres/gpu count reported lower than configured (3 < 4)
May 23 12:49:52 mgmt1.int.p2-ecole.calculquebec.cloud slurmctld[80708]: slurmctld: drain_nodes: node nodegpu1 state set to DRAIN
May 23 12:49:52 mgmt1.int.p2-ecole.calculquebec.cloud slurmctld[80708]: slurmctld: error: _slurm_rpc_node_registration node=nodegpu1: Invalid argument
May 23 12:49:56 mgmt1.int.p2-ecole.calculquebec.cloud slurmctld[1264181]: slurmctld: debug:  NodeNames=nodegpu1 setting Sockets=32 based on CPUs(32)/(CoresPerSocket(1)/ThreadsPerCore(1))
```

**Comment by mboisson** [comment] 2024-05-23 13:15
This is the commit that triggered the error https://github.com/calculquebec/mc-infra-ecole-parallel/commit/ea34ea0648e0ab0372abded48ae68e645c97e1e0

**Comment by cmd-ntrf** [comment] 2024-05-27 13:07
@etiennedub : I think the issue is triggered only when decreasing the number of partitions, as opposed to increasing it.

**Comment by etiennedub** [comment] 2024-06-06 15:26
Follow up on this issue. I tried to reproduce it but was not able to. I tried multiple approaches:

- Increase and decrease
- Disable/Enable
- Change configuration when a job is running and GPU is partially allocated.

I did try with the same parameters as @mboisson but also others.

@mboisson Was the issue frequent, or did it happen only one time?

**Comment by mboisson** [comment] 2024-06-06 15:31
This is not something I do often, so it only happened this one time.

**Comment by cmd-ntrf** [comment] 2024-07-17 13:10
Closing for now

**Closed by cmd-ntrf** 2024-07-17 13:10 UTC
Labels: bug
